schema_version = "1.0.0"

id = "fo2_bsa_import"
version = "1.0.0"
name = "FlatOut 2 Driver Animation (.bsa)"
tagline = "Import and export FlatOut 2 .bsa driver animations"
maintainer = "ravenDS <https://github.com/RavenDS>"
type = "add-on"

website = "https://github.com/RavenDS/flatout-blender-tools"
tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
